Remove the DPCTLQueueMgr_* and device_context API from dpctl
IntelPython/dpctl pull request #1576
Opened 2024-03-01 04:09 UTC by diptorupd

- [X] Have you provided a meaningful PR description?
The `DPCTLQueueMgr_*` implemented a global stack in libsyclinterface to keep track of a "current queue". The stack was controlled from dpctl's Python API using `dpctl.device_context`. Both these features are legacy design choices that have been abandoned right now and no longer are required.

The PR removes the DPCTLQueueMgr_*` interface, `dpctl.device_context` and all associated usages.

- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?
- [X] If this PR is a work in progress, are you opening the PR as a draft?

Fixes #11
Fixes #410
Fixes #1575

2024-03-16 21:24 UTC, oleksandr-pavlyk requested changes

2024-03-16 21:24 UTC, oleksandr-pavlyk commented on libsyclinterface/tests/test_sycl_usm_interface.cpp
> +    sycl::queue q;
I think we should use `DPCTLQueue_CreateForDevice` and create device from device selector

2024-03-18 20:57 UTC, oleksandr-pavlyk commented on libsyclinterface/tests/test_sycl_usm_interface.cpp
> +    sycl::queue q;
I pushed changes to implement my suggestion while rebasing this branch to resolve conflicts.

2024-03-19 01:38 UTC, oleksandr-pavlyk reviewed
This looks good to me know, but it would be best if `dpnp` can resolve its dependency on `DPCTLQueueMgr_*` before merging this. 

One option is to vendor implementation of `DPCTLQueueMgr_GetCurrentQueue` without implementing any code to modify the stack.

2024-03-19 02:06 UTC, diptorupd commented
> This looks good to me know, but it would be best if `dpnp` can resolve its dependency on `DPCTLQueueMgr_*` before merging this.
> 
> One option is to vendor implementation of `DPCTLQueueMgr_GetCurrentQueue` without implementing any code to modify the stack.

It is okay to wait for dpnp. Are there any blockers?

2024-03-20 12:19 UTC, oleksandr-pavlyk commented
`dpnp` pr IntelPython/dpnp#1735 has been merged. No blockers to merge this one.

2024-03-20 12:20 UTC, oleksandr-pavlyk approved these changes

2024-03-20 12:21 UTC, merged