Add descriptors
IntelPython/dpctl pull request #318
Opened 2021-03-11 13:02 UTC by 1e-to

Closes #317

2021-03-11 15:10 UTC, oleksandr-pavlyk commented
I think my comment on another PR applies here as well. 

On the Python side there is no need to ask for these descriptors at the time of `SyclDevice` construction. The query should be made on as-needed bases, i.e. when user queries the instance property.

This will avoid need to special-handle descriptors in case they are not supported for certain devices, like `max_sub_group_size` may not be supported on host device, and SYCL throws an exception.

2021-03-31 02:55 UTC, diptorupd requested changes
Rebase with master and update C API tests.

2021-03-31 02:55 UTC, diptorupd commented on dpctl-capi/source/dpctl_sycl_device_interface.cpp
> +#define declmethod(FUNC, NAME)                                                 \
You are really liking this style :+1:

2021-03-31 02:55 UTC, diptorupd commented on dpctl-capi/tests/test_sycl_device_interface.cpp
> +    if (!DRef)
See my comments in #315. Same apply here.

2021-04-07 16:41 UTC, oleksandr-pavlyk approved these changes

2021-04-07 16:51 UTC, diptorupd commented
@1e-to can you fix the merge conflicts. The macros in #315 and #318 should have different names.

2021-04-08 21:11 UTC, oleksandr-pavlyk approved these changes

2021-04-08 21:12 UTC, diptorupd approved these changes

2021-04-08 21:12 UTC, merged