Fixes names
IntelPython/dpctl pull request #378
Opened 2021-04-08 11:30 UTC by 1e-to

Closes #284

2021-04-08 16:20 UTC, diptorupd commented on dpctl-capi/include/dpctl_sycl_device_interface.h
> +DPCTLDevice_GetBackendVersion(__dpctl_keep const DPCTLSyclDeviceRef DRef);
This function does not need renaming. The SYCL function is called `get_backend` too.

2021-04-09 12:12 UTC, oleksandr-pavlyk requested changes
@1e-to Please revert the change to `DPCTLDevice_GetBackend` -> `DPCTLDevice_GetBackendVersion` per @diptorupd  comment.

2021-04-12 16:04 UTC, oleksandr-pavlyk commented on examples/cython/sycl_buffer/bench.py
> +        dpctl.get_current_queue().get_sycl_device().name,
Perhaps it should be `dpctl.get_current_queue().sycl_device.name` to simplify?

2021-04-12 16:04 UTC, oleksandr-pavlyk submitted a review, later dismissed
This is looking good. Thank you @1e-to

2021-04-13 02:39 UTC, oleksandr-pavlyk approved these changes

2021-04-13 03:49 UTC, diptorupd commented on dpctl-capi/include/dpctl_sycl_device_interface.h
> +DPCTLDevice_GetBackendVersion(__dpctl_keep const DPCTLSyclDeviceRef DRef);
@1e-to can make this change? I will like to have this change in 0.7.0.

2021-04-13 04:00 UTC, diptorupd commented on dpctl-capi/include/dpctl_sycl_device_interface.h
> +DPCTLDevice_GetBackendVersion(__dpctl_keep const DPCTLSyclDeviceRef DRef);
Oops missed your change. All set.

2021-04-13 04:06 UTC, diptorupd approved these changes

2021-04-13 04:08 UTC, merged