Add a new DPCTLEvent_GetWaitList function
IntelPython/dpctl pull request #510
Opened 2021-07-15 20:25 UTC by vlad-perevezentsev

This PR adds the 'DPCTLEvent_GetWaitList' function which returns the list of events that this event waits for in the dependence graph.

2021-07-19 14:58 UTC, oleksandr-pavlyk commented on dpctl-capi/include/dpctl_sycl_event_interface.h
> + * @brief  Return the vector of events that this event waits for
```suggestion
 * @brief  Returns the vector of events that this event still waits for
```

2021-07-19 14:59 UTC, oleksandr-pavlyk commented on dpctl-capi/include/dpctl_sycl_event_interface.h
> + * @brief  Return the vector of events that this event waits for
We should also say this is a wrapper around ``sycl::event::get_wait_list``.

2021-07-22 04:21 UTC, diptorupd commented on dpctl-capi/include/dpctl_sycl_event_interface.h
> +// Declares a set of types abd functions to deal with vectors of
Minor typo “and” instead of “abd”

2021-07-28 11:12 UTC, vlad-perevezentsev commented
@oleksandr-pavlyk I added a Sycl test for function.
It works on SYCL but  test fails with DPCTLSyclEvent.
```
/localdisk/work/vperevez/dp_dparray/dpctl_vlad/dpctl/dpctl-capi/tests/test_sycl_event_interface.cpp:158: Failure
Value of: DPCTLEventVector_Size(EVRef) > 0
  Actual: false
Expected: true
```

Dependencies passed via ' sycl:: handler::depends_on` are not included in the graph, but are tracked (Compiler LLVM team).
This is a bug. https://jira.devtools.intel.com/browse/CMPLRLLVM-30013

2021-08-02 23:57 UTC, oleksandr-pavlyk requested changes

2021-08-09 20:44 UTC, oleksandr-pavlyk approved these changes
I have applied the requested changes and resolved conflicts from earlier merges

2021-08-09 20:44 UTC, merged