Add a new DPCTLEvent_WaitAndThrow function
IntelPython/dpctl pull request #513
Opened 2021-07-27 11:02 UTC by vlad-perevezentsev

This PR adds a function 'DPCTLEvent_GetWaitList' which waits for the event to complete and calls the asynchronous error handler

2021-07-27 11:25 UTC, vlad-perevezentsev commented
@diptorupd  I added a sycl test that checks the call of the asynchronous error handler in the last commit.
Is it correct for this function?
Do I need to rewrite it via dpctl interface?
Can you tell me how better to write a test for this function?

2021-07-27 13:36 UTC, oleksandr-pavlyk commented
@vlad-perevezentsev please use backquotes rather than plain single quotes to delineate sycl object names.

2021-07-27 13:42 UTC, oleksandr-pavlyk commented
I suppose these tests will do for now, but I thought of using SYC C++ to create an event from submitting a kernel which causes a raise of an asynchronous exception to a queue with a custom handler that a side effect that a test checks for.

2021-08-03 18:10 UTC, oleksandr-pavlyk requested changes

2021-08-04 16:08 UTC, oleksandr-pavlyk approved these changes

2021-08-04 23:35 UTC, merged