[Refactoring] Add variables for skip decorators
IntelPython/dpctl pull request #684
Opened 2021-11-23 09:48 UTC by PokhodenkoSA

It could be reused in other tests.

2021-11-23 12:36 UTC, oleksandr-pavlyk reviewed
Why not move definitions of these decorators to `_helper.py`

This is where `has_gpu`, etc are defined anyway.

2021-11-23 13:50 UTC, PokhodenkoSA commented
Moving skips varibales to common place and reuse is the next step.

2021-11-23 13:59 UTC, PokhodenkoSA commented
Also pytest can skip the whole module if some clause not satisfied ([example](https://github.com/IntelPython/numba-dppy/blob/971298a68feb85f14bf0c6bdfbadde33c6f4af5f/numba_dppy/tests/test_debug_dppy_numba.py#L28)):
```python
pytestmark = pytest.mark.skipif(
    not shutil.which("gdb-oneapi"),
    reason="Intel® Distribution for GDB* is not available",
)
```

2021-11-23 14:02 UTC, PokhodenkoSA commented
> Why not move

If you agree that this style improves tests, then I will keep this style in my new code.

2021-11-23 21:32 UTC, oleksandr-pavlyk commented
Saving decorators as variables makes it more readable, but we are using programmatic way to skip tests based on `try/except` constructs in newer code, e.g.:

```python
try:
   q = dpctl.SyclQueue("cpu")
except dpctl.SyclQueueCreationError:
   pytest.skip("CPU queue could not be constructed")
```

2021-11-23 21:33 UTC, oleksandr-pavlyk approved these changes

2021-11-24 11:00 UTC, PokhodenkoSA commented
> we are using programmatic way to skip tests based on `try/except` constructs in newer code

This also could be checked in skip decorator.

2021-11-24 13:53 UTC, oleksandr-pavlyk commented
> This also could be checked in skip decorator. And this skip decorator could be transformed to variable.

It could, but use of decorator forces one to create a queue for the sake of checking in decorator, throw it away only to recreate it again in the body of the test.

2021-11-24 13:59 UTC, PokhodenkoSA commented
> throw it away only to recreate it again in the body of the test

It seems like a preliminary optimization. Why we need it?
We need to skip tests if we can not do some things. Moreover we will be able to do it on the level of module and only once. So it will be faster, just require reordering code in modules.

2021-11-30 15:19 UTC, oleksandr-pavlyk requested changes
This PR has become mangled, I am rescinding my approval until this is resolved, or PR is split into smaller chunks.

2021-12-01 09:14 UTC, PokhodenkoSA commented on CHANGELOG.md
> +
```suggestion
```

2021-12-01 09:16 UTC, PokhodenkoSA commented
Fixed PR: merge w/ master and target to master.

2021-12-03 12:03 UTC, oleksandr-pavlyk approved these changes
Please squash all commits into 1, since all the changes affect single file.

2021-12-03 13:23 UTC, PokhodenkoSA commented
> Please squash all commits into 1

You mean force squash and force push to the same branch?

2021-12-03 13:45 UTC, oleksandr-pavlyk commented
Or squash when merging, net effect is the same

2021-12-03 14:57 UTC, PokhodenkoSA commented
> net effect is the same

I think it is not the same. I will squash to one commit and you apply `Create a merge commit`. It will create 2 commits on target branch.
`squash when merging` will create only 1 commit on target branch.

2021-12-06 18:09 UTC, merged