Fix dpctl.lsplatform() to output in jupyter notebook
IntelPython/dpctl pull request #800
Opened 2022-03-25 10:46 UTC by vlad-perevezentsev

This PR changes `DPCTLPlatformMgr_PrintInfo` function to return `char *` instead of outputting it in `libsyclinterface` , and use that to print using CPython.

2022-03-25 17:40 UTC, oleksandr-pavlyk requested changes
Please do not change the API public functions. Instead extend the API and change the implementation of the API. 

`DPCTLPlatformMgr_PrintInfo` calls internal routine to get `std::string` and outputs it as before. 
`DPCTLPlatformMgr_GetInfo` calls internal routine to get `std::string` and copies the result into C-style string.

2022-03-28 14:49 UTC, oleksandr-pavlyk commented
@vlad-perevezentsev Thank you for making the requested changes. DPCTLSyclInterface tests for `DPCTLPlatformMgr_GetInfo` are also needed. 

The test would call a function and check that the returned `const char *` is not a nullptr.

2022-03-28 15:34 UTC, oleksandr-pavlyk commented on libsyclinterface/tests/test_sycl_platform_interface.cpp
> +    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,0);
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,0));
```

2022-03-28 15:34 UTC, oleksandr-pavlyk commented on libsyclinterface/tests/test_sycl_platform_interface.cpp
> +    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,0);
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,0));
```

2022-03-28 15:34 UTC, oleksandr-pavlyk commented on libsyclinterface/tests/test_sycl_platform_interface.cpp
> +    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,1);
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,1));
```

2022-03-28 15:34 UTC, oleksandr-pavlyk commented on libsyclinterface/tests/test_sycl_platform_interface.cpp
> +    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,2);
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,2));
```

2022-03-28 15:35 UTC, oleksandr-pavlyk commented on libsyclinterface/tests/test_sycl_platform_interface.cpp
> +    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,3);
```suggestion
    EXPECT_NO_FATAL_FAILURE(info_str = DPCTLPlatformMgr_GetInfo(PRef,3));
```

2022-03-28 16:31 UTC, oleksandr-pavlyk approved these changes
I was able to build the coverage workflow manually. I was also able to manually confirm that the original issue of output of `dpctl.lsplatform()` not showing in remotely connected jupyter notebook has been fixed. 

LGTM! Waiting for the CI to run its course.

2022-03-28 20:17 UTC, oleksandr-pavlyk approved these changes

2022-03-28 21:00 UTC, diptorupd approved these changes

2022-03-28 21:35 UTC, merged