Implemented dpctl.eye constructor and tests
IntelPython/dpctl pull request #896
Opened 2022-08-29 18:45 UTC by ndgrigorian

- [x] Have you provided a meaningful PR description?
- [x] Have you added a test, reproducer or referred to an issue with a reproducer?
- [x] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?
eye() returns an array with ones along the kth diagonal, and zeros elsewhere, and is implemented as per the array API standard specification

2022-08-30 13:32 UTC, oleksandr-pavlyk requested changes

2022-08-30 13:32 UTC, oleksandr-pavlyk commented on dpctl/tensor/_ctors.py
> +        order=order,
Here `order` does not matter, really, since contiguous 1D arrays are both C-contiguous and F-contiguous. It does not hurt either though.

2022-08-30 13:32 UTC, oleksandr-pavlyk commented on dpctl/tensor/_ctors.py
> +    if n_cols is None:
Since order is assumed in the code to be either `"C"` or `"F"`, perhaps argument validation is in order.

2022-08-30 13:32 UTC, oleksandr-pavlyk commented on dpctl/tests/test_usm_ndarray_ctor.py
> +def test_eye(shapes, k, orders):
Test should be exercising all supported array data types. Remember that some HW, like Iris Xe, does not support 64-bit floating point type, and hence does not support `complex128` by extension.

2022-09-12 20:56 UTC, ndgrigorian commented on dpctl/tensor/libtensor/source/tensor_py.cpp
> +    const py::ssize_t end = start + step * (length - 1) + 1;
Changed to step * (length - 1) as length N diagonal requires (N - 1) steps from start point to end point.

2022-09-12 21:42 UTC, oleksandr-pavlyk commented
I am seeing some compiler warnings:

```
~/dpctl/dpctl/tensor/libtensor/source/tensor_py.cpp:485:9: warning: unused parameter 'src_flags' [-Wunused-parameter]
    int src_flags,
        ^
~/dpctl/dpctl/tensor/libtensor/source/tensor_py.cpp:486:9: warning: unused parameter 'dst_flags' [-Wunused-parameter]
    int dst_flags,
        ^
2 warnings generated.
~/dpctl/dpctl/tensor/libtensor/source/tensor_py.cpp:485:9: warning: unused parameter 'src_flags' [-Wunused-parameter]
    int src_flags,
        ^
~/dpctl/dpctl/tensor/libtensor/source/tensor_py.cpp:486:9: warning: unused parameter 'dst_flags' [-Wunused-parameter]
    int dst_flags,
        ^
2 warnings generated.
```

2022-09-12 21:51 UTC, oleksandr-pavlyk commented
The following input `dpt.asnumpy(dpt.eye(5, k=1, dtype='c8', order='F'))` on WSL causes my driver to glitch. I will retry

2022-09-12 22:22 UTC, oleksandr-pavlyk commented
> The following input `dpt.asnumpy(dpt.eye(5, k=1, dtype='c8', order='F'))` on WSL causes my driver to glitch. I will retry, but the input hangs uninterruptibly too.

Must have been transient. Can not observe it anymore.

2022-09-13 00:00 UTC, oleksandr-pavlyk commented
Docstrings need some work:

![image](https://user-images.githubusercontent.com/21087696/189779053-fee00a1a-a965-4c8e-95d7-aa12d3d6115e.png)

2022-09-13 00:33 UTC, ndgrigorian commented
> Docstrings need some work:
> 
> ![image](https://user-images.githubusercontent.com/21087696/189779053-fee00a1a-a965-4c8e-95d7-aa12d3d6115e.png)

This should be fixed

2022-09-13 13:46 UTC, oleksandr-pavlyk approved these changes
Awesome! Thank you @ndgrigorian

2022-09-13 13:46 UTC, oleksandr-pavlyk commented
Can you please rebase your commit on top of master to get rid of merge commits and then we can merge it.

2022-09-13 15:45 UTC, ndgrigorian commented
> Can you please rebase your commit on top of master to get rid of merge commits and then we can merge it.

Done

2022-09-13 16:43 UTC, merged